### ISSUE TITLE
Persist applicant profile in database

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#35] opened 2021-12-28 17:32 UTC
- copy info from page one of the pre-screen application form: https://www.northerndevelopment.bc.ca/funding-programs/partner-programs/connecting-british-columbia/economic-recovery-intake/

- How do you qualify for this program. copy eligibility from FAQ (what are the eligibility requirements for the program)

- multiple questions to ensure applicants qualify

- textbox at the end for notes? (Raj)

**Comment by rgreensp** [comment] 2022-01-13 22:26
Closing. Duplicate of #81.

**Closed by rgreensp** 2022-01-13 22:26 UTC
Labels: Epic
