### ISSUE TITLE
Reporting Calendar

### ISSUE THREAD

**Issue by RajGurtata** [bcgov/connectivity-intake#291] opened 2022-03-23 20:57 UTC
As a user:

I want to be able to see what items are being reported on in what time period and on what date

So that:

We know what reports will need to be created/exported from the system

[https://bcgov.sharepoint.com/:x:/t/04708/EYhSUmXP1iJJkuszEKyoXn4BgECU7pzETHeHk3jkEie6iQ?e=34qmhN](url)

**Comment by rgreensp** [comment] 2022-03-29 16:54
Dupe of #293

**Closed as completed by rgreensp** 2022-03-29 16:54 UTC
